name: "Cooking App"
description: "recipe management for humans"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: Style/Formatting Check
      - run: npx prettier --check '.'
      - run: npm run build --if-present
    # will use whatever test script is specified in package.json (ie jest)
    # - run: npm test
